@startuml
class online.GameClientTest {
+ {static} Logger LOGGER
- {static} int port
- {static} String IP
+ {static} void main(String[])
}
enum Game.audio.GameAudio {
+  MENU_1
+  LEVEL_1
+  LEVEL_2
+  CREDITS
+  CLICK
+  HOLD
+  DIE
+  JUMP
+  GAMEOVER
+  LVL_COMPLETED
+  ATTACK_ONE
+  ATTACK_TWO
+  ATTACK_THREE
+  PLAYER_GET_HIT
+  ENEMY_ATTACK
+  ENEMY_DIE
+  ENEMY_FOUND_PLAYER
+ int arrayIndex
+ String fileName
+ {static} GameAudio[] allSongAudio
+ {static} GameAudio[] allUISoundsAudio
+ {static} GameAudio[] allEffectAudio
+ {static} GameAudio[] allAttackSound
+ {static} GameAudio[] allEnemyAttackEffectSound
~ <<Create>> GameAudio(int,String)
}
class Game.GUI.GameOptions {
- {static} Logger LOGGER
- GameAudioOptions gameAudioOptions
- BufferedImage backgroundImage
- GamePoint optionsPoints
- GameUnitPair optionsWH
- GameURMButton menuBtn
- List<GameUpdateInterface> allUpdateList
+ <<Create>> GameOptions(Game)
- void loadImage()
- void loadButtons()
+ void update()
+ void render(Graphics2D)
+ void mouseClicked(MouseEvent)
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
+ void mouseEntered(MouseEvent)
+ void mouseExited(MouseEvent)
+ void mouseDragged(MouseEvent)
+ void mouseMoved(MouseEvent)
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
}
class main.Main {
+ {static} void main(String[])
}
enum base.loader.FileNameFormatter {
+  TEXT
+  IMAGE
+  SOUND
- String fileType
~ <<Create>> FileNameFormatter(String)
+ String type()
+ {static} String of(String,FileNameFormatter)
}
class Game.DataPass {
+ {static} int[] stringDataToIntArray(String)
+ {static} double[] stringDataToDouble(String)
+ {static} T build(int[],Class<T>)
}
class online.InternetBase.InternetBaseClass {
# BufferedReader _inputStream
# PrintWriter _outStream
# Socket _sock
# <<Create>> InternetBaseClass(Socket)
+ void sendMessagePlug(String)
+ String recvMessagePlug()
+ void close()
}
abstract class Game.GUI.GameStateBase {
# Game game
+ <<Create>> GameStateBase(Game)
+ Game getGame()
+ boolean isIn(MouseEvent,GameMenuButton)
+ void setGameState(GameState)
}
class Game.GUI.ui.buttons.GameVolumeButton {
+ {static} int pitchesNumber
- BufferedImage[] image
- BufferedImage slider
- int buttonX
- int sliderMin
- {static} float sliderXOffset
- float floatValue
+ <<Create>> GameVolumeButton(GamePoint,BufferedImage[],BufferedImage)
# void initBounds()
+ void setImage(BufferedImage[])
+ void setSlider(BufferedImage)
+ void changeX(int)
- void updateFloatValue()
+ float getFloatValue()
+ void update()
+ void render(Graphics2D)
}
enum Game.gameBase.GameCalculator {
+  ADD
+  SUB
+  MUL
+  DIV
+ {static} GameUnitPair calculate(int,int,GameCalculator,int)
+ {static} GameUnitPair calculate(int,int,GameCalculatorLambda)
}
class Game.GUI.ui.GameAudioOptions {
- {static} Logger LOGGER
- GameSoundButton musicButton
- GameVolumeButton volumeButtons
- List<GameButtonBase> allButtons
- GameAudioPlayer gameAudioPlayer
+ <<Create>> GameAudioOptions(GameAudioPlayer)
- void createSoundButton()
- void createVolumeButtons()
+ void update()
+ void render(Graphics2D)
+ void mouseClicked(MouseEvent)
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
+ void mouseEntered(MouseEvent)
+ void mouseExited(MouseEvent)
+ void mouseDragged(MouseEvent)
+ void mouseMoved(MouseEvent)
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
}
class online.InternetBase.InternetFunction {
+ {static} String[] commandSplit(String)
+ {static} String commandJoin(String[])
+ {static} String commandJoin(List<String>)
}
class Game.Loader.ImageNamePath {
+ {static} String PLAYER_MAIN_CHARACTER
+ {static} String imagePath(String,String)
+ {static} String imagePath(String)
}
class Game.GUI.ui.GameLevelCompletedOverLayer {
- {static} Logger LOGGER
- GamePlaying gamePlaying
- GameURMButton menuButton
- BufferedImage image
- GamePoint point
- GameUnitPair bgWH
- List<GameButtonBase> allButtons
+ <<Create>> GameLevelCompletedOverLayer(GamePlaying)
- void initButtons()
- void initImage()
+ void update()
+ void render(Graphics2D)
+ void mouseClicked(MouseEvent)
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
+ void mouseEntered(MouseEvent)
+ void mouseExited(MouseEvent)
+ void mouseDragged(MouseEvent)
+ void mouseMoved(MouseEvent)
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
}
class Game.role.GameEnemy {
- {static} Logger LOGGER
+ {static} int levelDataID
- {static} float drawXOffset
- {static} GameLevel levelData
- Player player
- {static} float walkSpeed
- int flipX
- Rectangle2D.Float attackBox
- boolean findPlayer
+ <<Create>> GameEnemy()
+ <<Create>> GameEnemy(String,float,float,GameEnemyType,GameAudioPlayer)
+ <<Create>> GameEnemy(float,float,BufferedImage[][],GameAudioPlayer)
+ {static} void passLevelData(GameLevel)
+ void setGameAudioPlayer(GameAudioPlayer)
- void initAttackBox()
+ {static} void passOffset(float)
+ void passPlayer(Player)
+ void update()
- void updateAttackBox()
+ void render(Graphics2D)
- void drawAttackBox(Graphics)
+ void updatePosition()
- void moveX()
- void updateXPosAndBehavior()
- void updateYPos()
+ void setAnimationImage()
+ void setAnimationState()
}
class online.GameMainOnlinePlayer {
- GameClient client
- GameOnline gameOnline
+ <<Create>> GameMainOnlinePlayer()
+ void update()
# void checkAttack()
+ GameOnlineSetter setGameClient(GameClient)
+ GameOnlineSetter setGameOnline(GameOnline)
}
interface Game.PLUG.online.GameOnlineSetter {
+ GameOnlineSetter setGameClient(GameClient)
+ GameOnlineSetter setGameOnline(GameOnline)
}
class Game.gameBase.GamePoint {
+ <<Create>> GamePoint()
+ <<Create>> GamePoint(int,int)
+ <<Create>> GamePoint(float,float)
+ <<Create>> GamePoint(GameUnitPair)
+ <<Create>> GamePoint(Point)
+ {static} GamePoint buildGamePoint(int,int)
+ {static} GamePoint buildGamePoint(float,float)
+ {static} GamePoint buildGamePoint(GameUnitPair)
+ {static} GamePoint buildGamePoint(Point)
+ void addToX(float)
+ void subToX(float)
+ void mulToX(float)
+ void divToX(float)
+ void addToY(float)
+ void subToY(float)
+ void mulToY(float)
+ void divToY(float)
+ GamePoint getCopy()
+ boolean equals(Object)
+ String toString()
+ {static} double distance(GameUnitPair,GameUnitPair)
+ {static} GamePoint add(GameUnitPair,GameUnitPair)
+ {static} GamePoint sub(GameUnitPair,GameUnitPair)
+ {static} GamePoint mul(GameUnitPair,GameUnitPair)
+ {static} double dot(GameUnitPair,GameUnitPair)
}
interface Game.PLUG.gameMath.GameLambda {
+ T func(T,T)
}
class Game.GUI.ui.GamePauseDisplayLayer {
- BufferedImage backgroundImage
- GamePlaying gamePlaying
- GameAudioOptions gameAudioOptions
- GameUnitPair bgWH
- GamePoint bgPoint
- GameURMButton menuB
- List<GameButtonBase> allButtons
- {static} Logger LOGGER
+ <<Create>> GamePauseDisplayLayer(GamePlaying)
- void createURMButton()
- void loadBackground()
+ void update()
+ void render(Graphics2D)
+ void mouseClicked(MouseEvent)
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
+ void mouseEntered(MouseEvent)
+ void mouseExited(MouseEvent)
+ void mouseDragged(MouseEvent)
+ void mouseMoved(MouseEvent)
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
}
class Game.GUI.GameOnline {
- BufferedImage bgImage
+ {static} Logger LOGGER
- {static} int port
- GameLevelManager gameLevelManager
- String IP
- GameMainOnlinePlayer player
- GameOnlinePlayer gameOnlinePlayer
- String roomPlay
- String userName
- GameClient client
+ <<Create>> GameOnline(Game)
- void commandProcess(String)
- void loadImage()
- void initClient()
- void initClass()
+ void update()
+ void render(Graphics2D)
- void listenToServer()
+ void mouseClicked(MouseEvent)
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
+ void mouseEntered(MouseEvent)
+ void mouseExited(MouseEvent)
+ void mouseDragged(MouseEvent)
+ void mouseMoved(MouseEvent)
- void keyEventToPlayerMove(KeyEvent,boolean)
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
+ void setPlayerDying(boolean)
}
class Game.GUI.ui.buttons.GameMenuButton {
+ {static} int pitchesNumber
- {static} int xOffsetCenter
- GameState state
- BufferedImage[] images
+ <<Create>> GameMenuButton(GamePoint,BufferedImage[],GameState)
# void initBounds()
+ void update()
+ void render(Graphics2D)
+ void applyGameState()
}
class Game.Loader.GameElementLoader {
- {static} Logger LOGGER
- {static} BiFunction<String,GameAudio,Optional<Clip>> loadClipLambda
+ Player gameCharacter()
+ {static} Player getTestingGameCharacter()
+ {static} Player getTestingGameCharacter(String)
+ {static} BufferedImage[] loadBackgroundSkinImageFromTextList(String)
+ {static} Player loadCharacterByPath(String)
+ {static} int[][] loadGameLevelData(String,int,int)
+ {static} ArrayList<GameEnemy> loadGameEnemyData(String,int,int,BufferedImage[][],GameAudioPlayer)
+ {static} Clip[] loadClip(String,GameAudio[])
}
class Game.effects.Rain {
- {static} Logger LOGGER
- GamePoint[] drops
- SecureRandom random
- float rainSpeed
- BufferedImage rainImage
- float xLevelOffset
+ <<Create>> Rain()
- void loadImage()
- void initDrops()
- GamePoint getRandomPos()
- float getNewX()
+ void passOffset(float)
+ void update()
+ void render(Graphics2D)
}
class main.GameWindow {
+ <<Create>> GameWindow()
+ void init(GamePanel)
- WindowFocusListener settingWindowFocusListener(GamePanel)
}
class Game.GUI.UIConstant {
}
enum Game.GUI.MenuButtons {
+  B_WIDTH_DEFAULT
+  B_HEIGHT_DEFAULT
+  B_WIDTH
+  B_HEIGHT
+ int value
~ <<Create>> MenuButtons(int)
}
enum Game.GUI.PauseLayerButtons {
+  SOUND_SIZE_DEFAULT
+  SOUND_SIZE
+ int value
~ <<Create>> PauseLayerButtons(int)
}
enum Game.GUI.URMButtons {
+  URM_SIZE_DEFAULT
+  URM_SIZE
+ int value
~ <<Create>> URMButtons(int)
}
enum Game.GUI.VolumeButtons {
+  VOLUME_DEFAULT_WIDTH
+  VOLUME_DEFAULT_HEIGHT
+  SLIDER_DEFAULT_WIDTH
+  VOLUME_WIDTH
+  VOLUME_HEIGHT
+  SLIDER_WIDTH
+ int value
~ <<Create>> VolumeButtons(int)
}
enum Game.GUI.StatusBar {
+  STATUS_BAR_WIDTH
+  STATUS_BAR_HEIGHT
+  STATUS_BAR_X
+  STATUS_BAR_Y
+  HEALTH_BAR_WIDTH
+  HEALTH_BAR_HEIGHT
+  HEALTH_BAR_X_START
+  HEALTH_BAR_Y_START
+ int value
~ <<Create>> StatusBar(int)
}
class Game.Player {
- {static} Logger LOGGER
- int[][] levelData
- GameLevel level
# float drawXOffset
- BufferedImage statusBarImage
- int maxHealth
- int currentHealth
- int healthWidth
- Rectangle2D.Float attackBox
# int flipX
# int flipW
- boolean attackChecked
- GamePlaying gamePlaying
# boolean gameOverEffect
+ <<Create>> Player()
+ <<Create>> Player(AniData,ImageScaleData,GamePlayerSpeedData)
- void loadUIImage()
- void initAttackBox()
+ void initWithPoint_testing(float,float)
+ void init(float,float)
+ void setGamePlaying(GamePlaying)
+ Rectangle2D.Float getAttackBox()
+ void update()
# void checkAttack()
- void updateAttackBox()
+ void passOffset(float)
- void updateXPos()
- void updateYPos()
+ void changeHealth(int)
- void setHitAni()
+ void updatePosition()
- void updateImageDirection()
- void jump()
+ void render(Graphics2D)
- void drawAttackBox(Graphics)
# void drawUI(Graphics)
+ void setAnimationImage()
+ void setAnimationState()
+ void setLevelData(int[][])
+ void setLevel(GameLevel)
- void updateHealthBar()
# void updateAnimationTick()
+ void resetAll()
}
class Game.GUI.GameCredits {
- {static} Logger LOGGER
- BufferedImage bgImage
- GamePoint cdPoint
- GameUnitPair cdWH
- float cdYFloat
- ArrayList<ShowGameCharacter> gameCharacterList
+ <<Create>> GameCredits(Game)
- void initBackground()
- void initShowGameCharacter()
+ void update()
+ void render(Graphics2D)
+ void mouseClicked(MouseEvent)
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
+ void mouseEntered(MouseEvent)
+ void mouseExited(MouseEvent)
+ void mouseDragged(MouseEvent)
+ void mouseMoved(MouseEvent)
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
}
class Game.GUI.GameCredits.ShowGameCharacter {
- BufferedImage[] idleAnimationImage
- GamePoint point
- int aniIndex
+ <<Create>> ShowGameCharacter(String,GamePoint)
+ void update()
+ void render(Graphics2D)
}
class Game.audio.GameAudioPlayer {
- {static} Logger LOGGER
- Clip[] songs
- int currentSongId
- float volume
- boolean songMute
- Random random
- String folderPath
+ <<Create>> GameAudioPlayer(String)
- void loadUISoundEffects()
- void loadSongs()
- void loadEffects()
+ void setVolume(float)
+ void stopSong()
+ void setLevelSong(int)
+ void levelCompleted()
+ void playAttackSound()
+ void playEnemyAttackSound()
+ void playEffect(GameAudio)
+ void playUiEffect(GameAudio)
+ void stopUiEffect(GameAudio)
+ void playSong(GameAudio)
+ void toggleSongMute()
+ void toggleEffectMute()
- FloatControl clipToFloatControl(Clip)
- void updateSongVolume()
- void updateEffectsVolume()
+ void playLevelComplete()
}
enum Game.state.GameCharacterState {
+  IDLE
+  MOVING
+  JUMP
+  FALLING
+  ATTACKING
+  HIT
+  DEAD
+ int saveArrayIndex
+ int frameNumber
+ String imageString
~ <<Create>> GameCharacterState(int,int,String)
}
interface Game.PLUG.gameMath.GameCalculatorLambda {
+ int calculate(int)
}
class Game.GUI.ui.buttons.GameSoundButton {
- BufferedImage[][] soundImages
+ {static} int BUTTON_ROW_NUMBER
+ {static} int BUTTON_COLUMN_NUMBER
- boolean isMul
+ <<Create>> GameSoundButton(GamePoint)
+ boolean isMul()
+ void setMul(boolean)
+ void changeMul()
+ void setSoundImages(BufferedImage[][])
# void initBounds()
+ void update()
+ void render(Graphics2D)
}
class base.BaseGameConstant {
+ {static} int TILES_DEFAULT_SIZE
+ {static} float SCALE
+ {static} int TILES_IN_WIDTH
+ {static} int TILES_IN_HEIGHT
+ {static} int TILES_SIZE
+ {static} int GAME_WIDTH
+ {static} int GAME_HEIGHT
}
interface Game.PLUG.gameDrawer.GameRenderInterface {
+ void render(Graphics2D)
}
class Game.GUI.GamePlaying {
- {static} Logger LOGGER
- float leftBorder
- float rightBorder
- GameLevelManager gameLevelManager
- Player player
- GamePauseDisplayLayer gamePauseDisplayLayer
- boolean paused
- float xLevelOffset
- int levelTileWide
- int maxTileOffset
- int maxLevelOffset
- BufferedImage playingBackgroundImage
- BufferedImage cityImage2
- GameEnemyManager gameEnemyManager
- GameOverDisplayLayer gameOverDisplayLayer
- boolean gameOver
- boolean playerDying
- GameLevelCompletedOverLayer gameLevelCompletedOverLayer
- boolean levelComplete
- Rain rain
- boolean drawRaining
+ <<Create>> GamePlaying(Game)
+ void setPaused(boolean)
+ void initClass()
+ void loadNextLevel()
+ Player getPlayer()
+ void windowLostFocus()
+ void update()
- void checkCloseToBorder()
+ void render(Graphics2D)
- void drawCityImage(Graphics2D)
+ void resetAll()
+ void setGameOver(boolean)
+ void setPlayerDying(boolean)
+ void setLevelCompleted(boolean)
+ void checkEnemyHit(Player)
+ void mouseClicked(MouseEvent)
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
+ void mouseEntered(MouseEvent)
+ void mouseExited(MouseEvent)
+ void mouseDragged(MouseEvent)
+ void mouseMoved(MouseEvent)
- void keyEventToPlayerMove(KeyEvent,boolean)
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
}
class Game.GUI.ui.buttons.GameURMButton {
+ {static} int pitchesNumber
- BufferedImage[] image
+ <<Create>> GameURMButton(GamePoint,BufferedImage[])
+ void setImage(BufferedImage[])
+ void update()
+ void render(Graphics2D)
# void initBounds()
}
class online.GameOnlinePlayer {
- GameClient client
- GameOnline gameOnline
+ GameOnlineSetter setGameClient(GameClient)
+ GameOnlineSetter setGameOnline(GameOnline)
+ void update()
# void checkAttack()
+ void render(Graphics2D)
# void drawUI(Graphics)
+ void onlineCommandProcess(String)
}
class Game.GUI.ui.GameOverDisplayLayer {
- {static} Logger LOGGER
- GamePlaying gamePlaying
- BufferedImage deadDisplayImage
- GameUnitPair imageWH
- GamePoint imagePoint
- GameURMButton menuButton
- List<GameButtonBase> allButtons
+ <<Create>> GameOverDisplayLayer(GamePlaying)
- void loadImage()
- void loadButtons()
+ void update()
+ void render(Graphics2D)
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
+ void mouseClicked(MouseEvent)
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
+ void mouseEntered(MouseEvent)
+ void mouseExited(MouseEvent)
+ void mouseDragged(MouseEvent)
+ void mouseMoved(MouseEvent)
}
class online.GameClient {
+ {static} Logger LOGGER
- String userName
+ <<Create>> GameClient(String,int,String)
- void commandProcess(String)
+ Runnable listenedServer()
+ Runnable sendMessageConsole()
}
class logic.input.KeyboardInputs {
- Game game
+ <<Create>> KeyboardInputs(Game)
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
}
class main.Game {
- GameWindow gameWindow
- GamePanel gamePanel
- GameMenu gameMenu
- GamePlaying gamePlaying
- GameAudioOptions gameAudioOptions
- GameAudioPlayer gameAudioPlayer
- GameOptions gameOptions
- GameCredits gameCredits
- Thread gameThread
- {static} double FPS
- {static} double UPS
- int updates
- {static} Logger LOGGER
+ <<Create>> Game()
- void initClasses()
+ void runGame()
+ GameWindow getGameWindow()
+ void gameLogicUpdateThread()
+ void gameRenderThread()
+ void run()
+ GameMenu getGameMenu()
+ GamePlaying getGamePlaying()
+ void update()
+ void render(Graphics2D)
+ void windowLostFocus()
+ GameOptions getGameOptions()
+ GameAudioOptions getGameAudioOptions()
+ GameAudioPlayer getGameAudioPlayer()
+ GameCredits getGameCredits()
}
enum logic.input.Direction {
+  UP
+  DOWN
+  LEFT
+  RIGHT
+  NONE
+ String cmd
+ int index
~ <<Create>> Direction(String,int)
+ boolean isMoving()
}
class Game.gameBackground.GameEnemyManager {
- {static} Logger LOGGER
- GamePlaying gamePlaying
- BufferedImage[][] enemyImage
- List<GameEnemy> enemyArr
- Player player
- GameAudioPlayer gameAudioPlayer
+ <<Create>> GameEnemyManager(GamePlaying)
- void loadEnemyImage()
- void addEnemies()
+ {static} void passOffset(float)
+ {static} void passLevelData(GameLevel)
+ void passPlayer(Player)
+ void checkEnemyHit(Player)
+ void update()
+ void render(Graphics2D)
+ void resetAll()
}
abstract class Game.GUI.ui.buttons.GameButtonBase {
# GamePoint point
# MouseState mouseState
# Rectangle bounds
+ <<Create>> GameButtonBase(GamePoint)
+ MouseState getMouseState()
+ void setMouseState(MouseState)
+ Rectangle getBounds()
+ boolean isIn(MouseEvent)
+ void resetState()
+ void setPoint(GamePoint)
# {abstract}void initBounds()
}
class Game.GameElementFactory {
- {static} BiFunction<BufferedImage,Integer,BufferedImage[]> getURMImageByRow
+ <<Create>> GameElementFactory()
- {static} BufferedImage[] getGameMenuButton(BufferedImage,int)
+ {static} GameMenuButton[] getAllMenuButtons(float[],float[])
+ {static} GameSoundButton[] getAllGameSoundButton(GamePoint,GamePoint)
+ {static} GameURMButton[] getAllGameURMButton(GamePoint,GamePoint,GamePoint)
+ {static} GameVolumeButton getAllGameVolumeButton(GamePoint)
}
enum Game.role.GameEnemyType {
+  ENEMY_TYPE_1
+ int health
+ int damage
~ <<Create>> GameEnemyType(int,int)
}
abstract class Game.role.ABC.GameEnemyABC {
# GameEnemyType enemyType
# {static} float ATTACK_DISTANCE
# {static} float SEE_DISTANCE
# int maxHealth
# int currentHealth
# boolean firstUpdate
- boolean active
# boolean attackChecked
# GameAudioPlayer gameAudioPlayer
+ <<Create>> GameEnemyABC()
+ <<Create>> GameEnemyABC(GameEnemyType,GameAudioPlayer)
+ <<Create>> GameEnemyABC(AniData,ImageScaleData,GamePlayerSpeedData,GameEnemyType)
# void resetHealth(int)
+ boolean isActive()
+ GameEnemyType getEnemyType()
+ void setEnemyType(GameEnemyType)
+ void update()
+ int getAniIndex()
# void newEnemyState(GameCharacterState)
+ void getHurt(int)
# void checkPlayerGetHit(Rectangle2D.Float,Player)
+ GameCharacterState getEnemyState()
# void changeDirection()
# void turnTowardsPlayer(GameCharacterABC)
# boolean isPlayerInRange(GameCharacterABC)
# boolean isPlayerCloseForAttack(GameCharacterABC)
# boolean canSeePlayer(GameLevel,GameCharacterABC)
+ int getCurrentHealth()
+ void resetAll()
# void updateAnimationTick()
}
class logic.Controller.GameHelpMethods {
- {static} boolean outOfWindow(float,float,float)
- {static} boolean IsSolid(float,float,GameLevel)
+ {static} boolean IsTileSolid(float,float,GameLevel,boolean)
+ {static} boolean canMoveHere(GamePoint,float,float,GameLevel)
+ {static} boolean isOnTheFloor(GamePoint,float,float,GameLevel)
+ {static} boolean isFloor(GamePoint,float,int,int,GameLevel)
+ {static} boolean isFloor(GamePoint,float,float,GameLevel)
+ {static} boolean isAllTileWalkable(int,int,GameLevel,int)
+ {static} boolean isSightClear(GameLevel,GameCharacterABC,GameCharacterABC)
}
class logic.input.MouseInputs {
- Game game
+ <<Create>> MouseInputs(Game)
+ void mouseDragged(MouseEvent)
+ void mouseMoved(MouseEvent)
+ void mouseClicked(MouseEvent)
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
+ void mouseEntered(MouseEvent)
+ void mouseExited(MouseEvent)
}
enum Game.state.GameState {
+  PLAYING
+  MENU
+  OPTIONS
+  CREDITS
+  QUITS
- {static} GameState state
- {static} Logger LOGGER
+ {static} GameState[] MENU_GAME_STATES_CHOOSE
+ {static} GameState getState()
+ {static} void setState(GameState)
}
interface Game.PLUG.online.GameOnlineInterface {
}
class Game.GameSourceFilePath {
+ {static} String PLAYER_MAIN_CHARACTER_TEXT_FILE
+ {static} String BACKGROUND_IMAGE_PATH
+ {static} String BACKGROUND_IMAGE_PATH_CITY
+ {static} String BACKGROUND_SKIN_FOLDER_PATH
+ {static} String BACKGROUND_LEVEL_ONLINE
+ {static} String BACKGROUND_LEVEL_1
+ {static} String BACKGROUND_LEVEL_2
+ {static} String LEVEL_COMPLETED_IMAGE
+ {static} String PLAYING_BACKGROUND_IMAGE
+ {static} String PLAYING_BACKGROUND_IMAGE_CITY
+ {static} String MENU_BUTTON_IMAGE_1
+ {static} String MENU_BACKGROUND_IMAGE
+ {static} String MENU_SELECT_BACKGROUND_IMAGE
+ {static} String MENU_SELECT_BACKGROUND_IMAGE_CITY
+ {static} String CITY_BACKGROUND_2_IMAGE
+ {static} String CITY_BACKGROUND_3_IMAGE
+ {static} String CITY_BACKGROUND_4_IMAGE
+ {static} String CITY_BACKGROUND_5_IMAGE
+ {static} String PAUSE_BACKGROUND_IMAGE
+ {static} String SOUND_BUTTON_IMAGE
+ {static} String URM_BUTTON_IMAGE
+ {static} String VOLUME_BUTTON_IMAGE
+ {static} String STATUS_HEALTH_BAR_IMAGE
+ {static} String ENEMIES_FOLDER_PATH
+ {static} String DEAD_SCREEN_IMAGE
+ {static} String OPTIONS_IMAGE
+ {static} String AUDIO_FOLDER_PATH
+ {static} String RAINING_IMAGE
+ {static} String BOX_OBJECT_IMAGE
+ {static} String POTION_OBJECT_IMAGE
+ {static} String CREDITS_IMAGE
+ {static} String PYTHON_CHARACTER_FOLDER
+ {static} String CPP_CHARACTER_FOLDER
+ {static} String JAVA_CHARACTER_FOLDER
}
class Game.gameBackground.GameLevelManager {
- {static} Logger LOGGER
+ {static} int HEIGHT_BLOCK_NUM
+ {static} int WIDTH_BLOCK_NUM
+ {static} int MAX_NUMBER
+ {static} int PIXEL
- Game game
- BufferedImage[] bgMapImage
- GameLevel gameLevel1
- float drawXOffset
- int levelIndex
+ <<Create>> GameLevelManager(Game)
+ void setGameLevelFromFile(String)
+ void passOffset(float)
+ void render(Graphics2D)
+ GameLevel getGameLevel()
+ void update()
+ void loadNextLevel()
}
interface Game.PLUG.gameDrawer.GameUpdateInterface {
+ void update()
}
class Game.Loader.ImageLoader {
- {static} BiFunction<String,Integer,BufferedImage> loadImageLambda
+ {static} BufferedImage loadImage(String,String)
+ {static} BufferedImage loadImage(String)
- {static} BufferedImage[] loadCharacterImageByState(String,GameCharacterState)
+ {static} BufferedImage[][] loadCharacterImage(String,int,int)
+ {static} BufferedImage[] loadBackgroundImage(String,int,int,int)
}
interface Game.PLUG.gameDrawer.GameRenderOffsetPass {
~ void passOffset(float)
}
class main.GamePanel {
- Game game
- MouseInputs mouseInputs
- KeyboardInputs keyboardInputs
+ <<Create>> GamePanel(Game)
+ void init()
+ void paintComponent(Graphics)
+ Game getGame()
}
class Game.gameBackground.GameLevel {
- int[][] levelData
+ <<Create>> GameLevel(int[][])
+ {static} GameLevel loadFromFile(String)
+ int getImageIndex(int,int)
+ int getImageIndex(GameUnitPair)
+ int[][] getLevel2D()
+ int getMaxWidth()
}
class Game.GUI.GameMenu {
- {static} int MENU_BUTTON_NUMBER
- GameMenuButton[] buttons
- BufferedImage backgroundImage
- GameUnitPair menuWH
- GamePoint menuBgPoint
- {static} float[] xMenuArray
- {static} float[] yMenuArray
+ <<Create>> GameMenu(Game)
- void loadGameMenuSelectBackgroundImage()
- void loadGameMenuBackgroundImage()
- void loadGameMenuButton()
+ void render(Graphics2D)
+ void update()
+ void mouseClicked(MouseEvent)
+ void mousePressed(MouseEvent)
+ void mouseReleased(MouseEvent)
- void resetButtons()
+ void mouseEntered(MouseEvent)
+ void mouseExited(MouseEvent)
+ void mouseDragged(MouseEvent)
+ void mouseMoved(MouseEvent)
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
}
class Game.gameBase.GameUnitPair {
+ float x
+ <<Create>> GameUnitPair()
+ <<Create>> GameUnitPair(int,int)
+ <<Create>> GameUnitPair(float,float)
+ <<Create>> GameUnitPair(Point)
+ <<Create>> GameUnitPair(GameUnitPair)
+ {static} GameUnitPair buildGameUnitPair(int,int)
+ {static} GameUnitPair buildGameUnitPair(float,float)
+ {static} GameUnitPair buildGameUnitPair(Point)
+ GameUnitPair getPoint()
+ Point toIntPoint()
+ void setAll(float,float)
+ GameUnitPair getSizePoint()
+ void copy(GameUnitPair)
+ void copy(Point)
+ GameUnitPair getCopy()
+ GameUnitPair add(float)
+ GameUnitPair sub(float)
+ GameUnitPair mul(float)
+ GameUnitPair div(float)
+ void setX(float)
+ void setY(float)
+ float getX()
+ float getY()
+ int getIntX()
+ int getIntY()
+ void setW(float)
+ void setH(float)
+ float getW()
+ float getH()
+ int getIntW()
+ int getIntH()
}
class Game.builder.GameCharacterBuilder {
- Player gameCharacter
+ <<Create>> GameCharacterBuilder()
+ GameCharacterBuilder setAniData(AniData)
+ GameCharacterBuilder setImageScale(ImageScaleData)
+ GameCharacterBuilder setGamePlayerSpeedData(GamePlayerSpeedData)
+ GameCharacterBuilder setAnimationImage(String,int,int)
+ Player build()
}
abstract class Game.role.ABC.BasicGameCharacterABC {
+ {static} int HIT_BOX_WIDTH
+ {static} int HIT_BOX_HEIGHT
# GameCharacterState gameCharacterState
# boolean attacking
# GamePoint point
# float playerSpeed
# Direction direction
# int[] dirMove
# Rectangle2D.Float hitBox
# float airSpeed
# float gravity
# float jumpSpeed
# float fallSpeedAfterCollision
# boolean inAir
+ <<Create>> BasicGameCharacterABC()
+ <<Create>> BasicGameCharacterABC(GameCharacterState,GamePoint,Direction,boolean)
+ {abstract}void updatePosition()
# void initHitBox(GamePoint,int,int)
# void initHitBox()
# void updateHitBox()
+ Rectangle2D.Float getHitBox()
# void drawHitBox(Graphics,float)
# void resetInAir()
+ void setX(float)
+ void setY(float)
+ void setResetPoint(GamePoint)
+ GamePoint getGamePoint()
+ void setXY(float,float)
# void setPlayerSpeed(float)
+ void setAttacking(boolean)
+ void setCharacterState(GameCharacterState)
+ void stopDirection()
+ void setDirection(Direction,boolean)
+ void setJump(boolean)
+ void resetAll()
}
class base.loader.BaseLoader {
- {static} Logger LOGGER
- {static} String pathToAbsolutePath(String)
+ {static} InputStream loadFile(String)
+ {static} BufferedImage convertToImage(InputStream)
+ {static} BufferedImage loadImage(String)
+ {static} URI getURI(Class<T>,String)
+ {static} List<String> loadTextFile(String)
+ {static} Clip loadClip(String)
}
enum Game.state.MouseState {
+  OVER
+  PRESS
+  NONE
+ int toDisplayIndex
~ <<Create>> MouseState(int)
}
enum online.InternetBase.InternetConstant {
+  SUCCESS
+  FAIL
+  NONE
+  ERROR
+  OK
- String command
~ <<Create>> InternetConstant(String)
+ String toString()
}
interface Game.PLUG.GameStateMethod {
}
interface Game.PLUG.gameDrawer.GameAnimatedDrawer {
}
abstract class Game.role.ABC.GameCharacterABC {
# BufferedImage[][] animations
# int aniTick
# int imgScaleX
# float pushDrawOffset
# Direction pushBackDir
+ <<Create>> GameCharacterABC()
+ <<Create>> GameCharacterABC(AniData,ImageScaleData,GamePlayerSpeedData)
+ void setAniThing(AniData)
+ void setImageScale(ImageScaleData)
+ void setGamePlayerSpeedData(GamePlayerSpeedData)
+ void setAnimation(BufferedImage[][])
+ void setAnimationImage(String)
# void resetAniTick()
# void newState(GameCharacterState)
# void updateAnimationTick()
+ BufferedImage getAnimationImage(GameCharacterState,int)
- int scaleFunction(int)
+ GameUnitPair getImageScalePoint(BufferedImage)
+ {abstract}void setAnimationImage()
+ {abstract}void setAnimationState()
# void updatePushBackDrawOffset()
# void pushBack(Direction,GameLevel,float)
}


Game.PLUG.GameStateMethod <|.. Game.GUI.GameOptions
Game.GUI.GameStateBase <|-- Game.GUI.GameOptions
Game.GUI.ui.buttons.GameButtonBase <|-- Game.GUI.ui.buttons.GameVolumeButton
Game.PLUG.GameStateMethod <|.. Game.GUI.ui.GameAudioOptions
Game.PLUG.GameStateMethod <|.. Game.GUI.ui.GameLevelCompletedOverLayer
Game.role.ABC.GameEnemyABC <|-- Game.role.GameEnemy
Game.PLUG.online.GameOnlineSetter <|.. online.GameMainOnlinePlayer
Game.Player <|-- online.GameMainOnlinePlayer
Game.gameBase.GameUnitPair <|-- Game.gameBase.GamePoint
Game.PLUG.GameStateMethod <|.. Game.GUI.ui.GamePauseDisplayLayer
Game.PLUG.GameStateMethod <|.. Game.GUI.GameOnline
Game.GUI.GameStateBase <|-- Game.GUI.GameOnline
Game.GUI.ui.buttons.GameButtonBase <|-- Game.GUI.ui.buttons.GameMenuButton
Game.PLUG.gameDrawer.GameAnimatedDrawer <|.. Game.effects.Rain
Game.PLUG.gameDrawer.GameRenderOffsetPass <|.. Game.effects.Rain
javax.swing.JFrame <|-- main.GameWindow
Game.PLUG.gameDrawer.GameAnimatedDrawer <|.. Game.Player
Game.PLUG.gameDrawer.GameRenderOffsetPass <|.. Game.Player
Game.role.ABC.GameCharacterABC <|-- Game.Player
Game.PLUG.GameStateMethod <|.. Game.GUI.GameCredits
Game.GUI.GameStateBase <|-- Game.GUI.GameCredits
Game.GUI.GameCredits +.. Game.GUI.GameCredits.ShowGameCharacter
Game.GUI.GameAnimatedDrawer <|.. Game.GUI.GameCredits.ShowGameCharacter
Game.GUI.ui.buttons.GameButtonBase <|-- Game.GUI.ui.buttons.GameSoundButton
Game.PLUG.GameStateMethod <|.. Game.GUI.GamePlaying
Game.GUI.GameStateBase <|-- Game.GUI.GamePlaying
Game.GUI.ui.buttons.GameButtonBase <|-- Game.GUI.ui.buttons.GameURMButton
Game.PLUG.online.GameOnlineSetter <|.. online.GameOnlinePlayer
Game.Player <|-- online.GameOnlinePlayer
Game.PLUG.GameStateMethod <|.. Game.GUI.ui.GameOverDisplayLayer
online.InternetBase.InternetBaseClass <|-- online.GameClient
java.awt.event.KeyListener <|.. logic.input.KeyboardInputs
main.Runnable <|.. main.Game
Game.PLUG.gameDrawer.GameAnimatedDrawer <|.. main.Game
base.BaseGameConstant <|-- main.Game
Game.PLUG.gameDrawer.GameAnimatedDrawer <|.. Game.gameBackground.GameEnemyManager
Game.PLUG.gameDrawer.GameAnimatedDrawer <|.. Game.GUI.ui.buttons.GameButtonBase
Game.PLUG.gameDrawer.GameAnimatedDrawer <|.. Game.role.ABC.GameEnemyABC
Game.role.ABC.GameCharacterABC <|-- Game.role.ABC.GameEnemyABC
java.awt.event.MouseListener <|.. logic.input.MouseInputs
java.awt.event.MouseMotionListener <|.. logic.input.MouseInputs
Game.PLUG.gameDrawer.GameAnimatedDrawer <|.. Game.gameBackground.GameLevelManager
Game.PLUG.gameDrawer.GameRenderOffsetPass <|.. Game.gameBackground.GameLevelManager
javax.swing.JPanel <|-- main.GamePanel
Game.PLUG.GameStateMethod <|.. Game.GUI.GameMenu
Game.GUI.GameStateBase <|-- Game.GUI.GameMenu
Game.PLUG.gameDrawer.GameAnimatedDrawer <|-- Game.PLUG.GameStateMethod
java.awt.event.MouseListener <|-- Game.PLUG.GameStateMethod
java.awt.event.MouseMotionListener <|-- Game.PLUG.GameStateMethod
java.awt.event.KeyListener <|-- Game.PLUG.GameStateMethod
Game.PLUG.gameDrawer.GameUpdateInterface <|-- Game.PLUG.gameDrawer.GameAnimatedDrawer
Game.PLUG.gameDrawer.GameRenderInterface <|-- Game.PLUG.gameDrawer.GameAnimatedDrawer
Game.role.ABC.BasicGameCharacterABC <|-- Game.role.ABC.GameCharacterABC
@enduml